apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nats-server
subjects:
- kind: ServiceAccount
  name: nats-server
  namespace: default
---
# This resource creates a service where the port name must be renamed to
# tcp-client otherwise istio does not know how to forward traffic to the
# endpoints.
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: queue
spec:
  size: 1
  version: 2.1.9
  pod:
    enableClientHostPort: true
    advertiseExternalIP: true
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
  template:
    spec:
      serviceAccountName: nats-server
