apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-1-9-3
  namespace: istio-system
spec:
  components:
    base:
      k8s:
        overlays:
        - kind: ValidatingWebhookConfiguration
          name: istiod-istio-system
          patches:
          - path: webhooks.[name:validation\.istio\.io].clientConfig.service.name # << json path to reach the target value to fix
            value: istiod-1-9-3
    ingressGateways:
    - enabled: true
      k8s:
        env:
        # sni-dnat adds the clusters required for AUTO_PASSTHROUGH mode
        - name: ISTIO_META_ROUTER_MODE
          value: "sni-dnat"
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tls
            port: 15443
            targetPort: 15443
          - name: tls-istiod
            port: 15012
            targetPort: 15012
          - name: tls-webhook
            port: 15017
            targetPort: 15017
      label:
        app: istio-eastwestgateway
        istio: eastwestgateway
      name: istio-eastwestgateway
    - enabled: true
      label:
        app: istio-ingressgateway
        istio: ingressgateway
      name: istio-ingressgateway
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  revision: 1-9-3
  values:
    global:
      defaultPodDisruptionBudget:
        enabled: true
    telemetry:
      enabled: true
      v2:
        enabled: true
        stackdriver:
          enabled: true
